## Data Preprocessing

## Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Import Dataset

In [2]:
dataset = pd.read_csv("Data.csv")
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

## Solve for missing data

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:,1:3])


In [6]:
print(x)

[['India' 44.0 72000.0]
 ['Thailand ' 27.0 48000.0]
 ['Indonesia' 30.0 54000.0]
 ['China' 38.0 61000.0]
 ['India' 40.0 62562.5]
 ['China' 35.0 58000.0]
 ['Thailand ' 38.5625 52000.0]
 ['India' 48.0 79000.0]
 ['Indonesia' 50.0 83000.0]
 ['Thailand ' 37.0 67000.0]
 ['India' 25.0 62562.5]
 ['Thailand ' 36.0 60000.0]
 ['Indonesia' 42.0 64000.0]
 ['India' 38.5625 40000.0]
 ['Thailand ' 52.0 90000.0]
 ['Indonesia' 38.5625 55000.0]
 ['China' 41.0 62562.5]
 ['India' 29.0 48000.0]
 ['China' 43.0 70000.0]]


## Encoding the categorical data

## Encoding Independent variable

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 40.0 62562.5]
 [1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 38.5625 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 1.0 37.0 67000.0]
 [0.0 1.0 0.0 0.0 25.0 62562.5]
 [0.0 0.0 0.0 1.0 36.0 60000.0]
 [0.0 0.0 1.0 0.0 42.0 64000.0]
 [0.0 1.0 0.0 0.0 38.5625 40000.0]
 [0.0 0.0 0.0 1.0 52.0 90000.0]
 [0.0 0.0 1.0 0.0 38.5625 55000.0]
 [1.0 0.0 0.0 0.0 41.0 62562.5]
 [0.0 1.0 0.0 0.0 29.0 48000.0]
 [1.0 0.0 0.0 0.0 43.0 70000.0]]


## Encoding the dependent Variable

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[0 1 0 0 1 1 0 1 0 1 0 0 1 1 1 0 1 0 1]


## Splitting the dataset into the Train and Test set

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [14]:
print(x_test)

[[0.0 1.0 0.0 0.0 25.0 62562.5]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 43.0 70000.0]]


## Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [19]:
print(x_test)

[[-0.5         1.41421356 -0.5        -0.60302269 -2.45567606  0.07474013]
 [-0.5        -0.70710678 -0.5         1.6583124  -2.10929801 -1.15162956]
 [-0.5        -0.70710678  2.         -0.60302269  1.87404958  1.79586841]
 [ 2.         -0.70710678 -0.5        -0.60302269  0.6617264   0.70108345]]
